version: "3.2"
services:
    #PHP with apache
    ecommerce_container:
      #image will be built by processing the Dockerfile in this path
      build: .
      container_name: ecommerce_cont
      command:
        sh ./dock-files/startup.sh
      environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
      links:
        - ecommerce_db
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ecommerce_container.rule=Host(`ecommerce.localhost`)"
        - "traefik.http.routers.ecommerce_container.entrypoints=web"
        - "traefik.port=80"
      #map host folders (relative to this file) to service
      volumes:
        # - ./public/:/var/www/html
        - ./:/var/www/html
      #mark the db services as a dependency
      depends_on:
        - ecommerce_db
      restart:
        always
      networks:
        - traefik_webgateway
        - internal
      ports:
        - "8076:80"
        - 6006:6001
    #mysql db
    ecommerce_db:
      image: mysql:5.7.20
      # build: ./dock-files/MySqlDB
      container_name: ecommerce-mysql-database
      command: --sql_mode=""
      restart: always
      #storing the mysql folder outside allows persistence
      volumes:
        - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: mysql_root_password1
        MYSQL_USER: user
        MYSQL_PASSWORD: mysql_user_password1
        MYSQL_DATABASE: ecommerce_demo
      labels:
        - "traefik.enable=false"
      networks:
        internal:
          aliases:
            - ecommerce_mysql
      ports:
      - "4318:3306"
volumes:
    db_data:
    redis_data:
    data01:
networks:
  traefik_webgateway:
    external: true
  internal:
    external: true
